### ISSUE TITLE
Reset ability for FW output

### ISSUE THREAD

**Issue by bobjersey** [phuse-org/SEND-TestDataFactory#19]
and also add time and dose response as being done for BW

**Comment by ksny** [comment]
Get the FW domain working with the configuration file (use BW domain as guide)

**Comment by elimillera** [comment]
Hey @bobjersey @ksny ,
I have the FW domain working. I was looking at the time dose response for the BW and that looks like it relies on the BG domain. I might be out of the loop on how we wanted to implement this, but here is the idea I had. I was thinking we would have a second set of configurations for dose and time response. So `./configs/response` would detail the changes over a given domain for each species, strain, sex, dose group, and test by having a column detail a constant and a slope to modify the mean found in the original config.

I think that would be easier than adding extra columns to the existing configs but let me know if there are other ideas

**Comment by elimillera** [comment]
Closed in PR #25
